name: Civia
favicon: null
layout_spectrum: 0.5063522958662361
typography_spectrum: 0.5212882107589394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9260768578387797
  lightness: 0.20655619259923697
  saturation: 0.22451717196963727
  rhythmicContrast: 0.8380577315110713
purpose: []
